version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_pass
      MYSQL_ROOT_PASSWORD: dev_pass
    mem_limit: 256m
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --lower-case-table-names=1,
        --default-authentication-plugin=mysql_native_password
      ]
    volumes:
       - ./db_dev:/var/lib/mysql

volumes:
  db_dev:
