name: Django CI

on: [pull_request, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: core
          MYSQL_USER: dev
          MYSQL_ROOT_PASSWORD: dev_pass
          MYSQL_PASSWORD: dev_pass
        ports: ['3306:3306']
        command:
          [
            --character-set-server=utf8mb4,
            --collation-server=utf8mb4_unicode_ci,
            --lower-case-table-names=1,
            --default-authentication-plugin=mysql_native_password
          ]


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: extractions/setup-just@v1
      with:
        just-version: '1.4.0'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Setup a local virtual environment (if no poetry.toml file)
      run: just setup
    - name: Define a cache for the virtual environment based on the dependencies lock file
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - name: Install the project dependencies
      run: just install
    - name: Linting
      run: just lint
    - name: Migrations
      run: just migrations
    - name: Testing and coverage report
      run: just coverage
